apps/cart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import AddView, CartView, CartUpdateView, CartDeleteView

urlpatterns = [
	url(r'^add$', AddView.as_view(), name='add'),
	url(r'^main_cart$', CartView.as_view(), name='main_cart'),
	url(r'^update$', CartUpdateView.as_view(), name='update'),
	url(r'^delete$', CartDeleteView.as_view(), name='delete'),
]

apps/goods/urls.py
from django.conf.urls import url
from . import views
from apps.goods.views import DetailView, ListView

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^detail/(?P<sku_id>\d+)$', DetailView.as_view(), name='detail'),
	url(r'^list/(?P<spu_id>\d+)/(?P<page_num>\d+)$', ListView.as_view(), name='list'),
]

apps/user/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import RegisterView, ActiveView, LoginView, UserInfoView, UserAddressView, UserOrderView, LogoutView

urlpatterns = [
	# url(r'^register', register, name='register'),
	url(r'^register/$', RegisterView.as_view(), name='register'),
	url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),
	url(r'^login/', LoginView.as_view(), name='login'),
	url(r'^logout/', LogoutView.as_view(), name='logout'),
	url(r'^user-center-info/', UserInfoView.as_view(), name='user_center_info'),
	url(r'^user-center-order/', UserOrderView.as_view(), name='user_center_order'),
	url(r'^user-center-site/', UserAddressView.as_view(), name='user_center_site'),
]

dailyfresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('apps.user.urls', namespace='user')),
    url(r'^order/', include('apps.order.urls', namespace='order')),
    url(r'^cart/', include('apps.cart.urls', namespace='cart')),
    url(r'^search/', include('haystack.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('apps.goods.urls', namespace='goods')),
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django_redis import get_redis_connection
from django.http import JsonResponse
from apps.goods.models import GoodsSKU
from utils.loginrequiredmixin import LoginRequiredMixin

# Create your views here.


class AddView(View):
	def post(self, request):
		user = request.user
		sku_id = request.POST.get('sku_id')
		count = request.POST.get('count')
		count = int(count)
		goods_sku = GoodsSKU.objects.get(id=sku_id)

		if not user.is_authenticated():
			return JsonResponse({'res': 0, 'errmsg': '用户未登录'})
		# 校验数据完整性
		if not all([sku_id, count]):
			return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

		conn = get_redis_connection('default')
		cart_key = 'cart_%d' % user.id
		cart_count = conn.hget(cart_key, sku_id)
		if cart_count:
			cart_count = int(cart_count.decode())
			count += cart_count
			if count > goods_sku.stock:
				return JsonResponse({'res': 2, 'errmsg': '库存不足'})
		conn.hset(cart_key, sku_id, count)
		total_count = conn.hlen(cart_key)
		return JsonResponse({'res': 3, 'total_count': total_count, 'errmsg': '添加成功'})


class CartView(LoginRequiredMixin, View):
	def get(self, request):
		conn = get_redis_connection('default')
		user = request.user
		cart_key = 'cart_%d' % user.id
		cart_dict = conn.hgetall(cart_key)
		total_price = 0
		total_count = 0
		sku_list = []
		for sku_id, count in cart_dict.items():
			sku_id = sku_id.decode()
			goods_sku = GoodsSKU.objects.get(id=sku_id)
			count = int(count.decode())
			goods_sku.count = count
			amount = goods_sku.price * count
			goods_sku.amount = amount
			sku_list.append(goods_sku)
			total_count += count
			total_price += amount

		context = {
			'total_price': total_price,
			'total_count': total_count,
			'sku_list': sku_list,
		}
		return render(request, 'cart.html', context)


class CartUpdateView(View):
	def post(self, request):
		user = request.user
		sku_id = request.POST.get('sku_id')
		count = request.POST.get('count')
		sku = GoodsSKU.objects.get(id=sku_id)

		if not user.is_authenticated():
			return JsonResponse({'res': 0, 'errmsg': '用户未登录'})
		# 校验数据完整性
		if not all([sku_id, count]):
			return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
		if int(count) > sku.stock:
			return JsonResponse({'res': 2, 'errmsg': '库存不足'})

		conn = get_redis_connection('default')
		cart_key = 'cart_%d' % user.id
		conn.hset(cart_key, sku_id, count)
		return JsonResponse({'res': 3, 'errmsg': '更新成功', 'sku_id': sku_id, 'count': count})


class CartDeleteView(View):
	def post(self, request):
		user = request.user
		sku_id = request.POST.get('sku_id')
		cart_key = 'cart_%d' % user.id
		if not user.is_authenticated():
			return JsonResponse({'res': 0, 'errmsg': '未登录'})

		if not sku_id:
			return JsonResponse({'res': 1, 'errmsg': '商品不存在'})

		conn = get_redis_connection('default')
		conn.hdel(cart_key, sku_id)
		return JsonResponse({'res': 2, 'errmsg': '删除成功'})

templates/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {#网络标题内容块#}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main(1).css' %}">

    {# 网络顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{% block header_content %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if request.user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
                </div>
                <div class="login_btn fl">
                    <a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:main_cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:user_center_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_content %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo02.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

    {% block bottom %}{% endblock bottom %}

	{% block bottom_files %}{% endblock bottom_files %}
</body>
</html>

templates/base_detail_list.html
{% extends 'base.html' %}



{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="#" class="fruit">{{ type.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_no_cart.html
{% extends 'base.html' %}
{% load static %}

{% block search_bar %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

templates/base_user_center.html
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜用户中心{% endblock %}
{% block page_title %}用户中心{% endblock %}
{% block body %}
<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_info' %}" {% if page == 'info' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:user_center_order' %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:user_center_site' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {% block right_content %}{% endblock right_content %}
</div>
{% endblock %}

templates/detail.html
{% extends 'base_detail_list.html' %}
{% load static %}
 
{% block main_content %}

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ goods_sku.type.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ goods_sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods_sku.name }}</h3>
			<p>{{ goods_sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goods_sku.price }}</em></span>
				<span class="show_unit">单  位：{{ goods_sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" name="num" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em></em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
                {% csrf_token %}
				<a href="javascript:;" class="add_cart" sku_id={{ goods_sku.id }} id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for good_sku in new_goods_skus %}
					<li>
						<a href="{% url 'goods:detail' good_sku.id %}"><img src="{{ good_sku.image.url }}"></a>
						<h4><a href="#">{{ good_sku.name }}</a></h4>
						<div class="prize">￥{{ good_sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods_sku.goods.detail | safe }}</dd>
				</dl>
			</div>

            <div class="tab_content">
				<dl>
                    {% for order_good in order_goods %}
                        <dt>评论时间：{{ order_good.update_time }}&nbsp;&nbsp;用户名：{{ order_good.order.user.username }}</dt>
                        <dd>{{ order_goods.comment }}</dd>
                    {% empty %}
                    无评论
                    {% endfor %}
				</dl>
			</div>

		</div>
	</div>


	<div class="add_jump"></div>
{% endblock main_content %}

{% block bottom_files %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
    update_goods_amount()
    // 计算商品总价格
    function update_goods_amount() {
        // 获取价格
        price = $('.show_pirze').children('em').text()
        // 获取数量
        count = $('.num_show').val()
        // 计算商品总价格
        price = parseFloat(price)
        count = parseInt(count)
        amount = price*count
        $('.total').children('em').text(amount.toFixed(2))
    }

    $('.add').click(function () {
        //获取商品原有数目
        count = $('.num_show').val()
        count = parseInt(count)+1
        $('.num_show').val(count)
        update_goods_amount()
    })

    $('.minus').click(function () {
        //获取商品原有数目
        count = $('.num_show').val()
        count = parseInt(count)-1
        if(count <= 0 ){
            count = 1
        }
        $('.num_show').val(count)
        update_goods_amount()
    })

		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
		    // 获取sku+id, count
            sku_id = $(this).attr('sku_id')
            count = $('.num_show').val()
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'sku_id': sku_id, 'count': count, 'csrfmiddlewaretoken': csrf}
            // 发起ajax post 请求
            $.post('/cart/add', params, function (data) {
                if (data.res == 3){
                    // 添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                $('#show_count').html(data.total_count);
					        });
			        });

                }
                else{
                    alert(data.errmsg)
                }

            })
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});

			});
		})
	</script>
{% endblock bottom_files %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in type_goods_banners %}
				    <li><img src="{{ banner.image.url }}" alt="幻灯片"></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			<a href="#"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
            {% for banner in type.title_banners %}
				<a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
            {% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>
        <div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

{% block bottom_files %}
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock bottom_files%}

templates/list.html
{% extends 'base_detail_list.html' %}

{% block main_content %}

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="../static/images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="../static/images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' goods_type.id 1 %}?sort=default" class="active">默认</a>
				<a href="{% url 'goods:list' goods_type.id 1 %}?sort=price">价格</a>
				<a href="{% url 'goods:list' goods_type.id 1 %}?sort=hot">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku_good in page_con %}
				<li>
					<a href="detail.html"><img src="{{ sku_good.image.url }}"></a>
					<h4><a href="detail.html">{{ sku_good.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku_good.price }}</span>
						<span class="unit">{{ sku_good.price }}/{{ sku_good.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
            </ul>

			<div class="pagenation">
                {% if page_con.has_previous %}
				<a href="{% url 'goods:list' goods_type.id page_con.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}
                {% for num in pages %}
				<a href="{% url 'goods:list' goods_type.id num %}?sort={{ sort }}" {% if num == page_con.number %}class="active"{% endif %}> {{ num }}</a>
                {% endfor %}
                {% if page_con.has_next %}
				<a href="{% url 'goods:list' goods_type.id page_con.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock main_content%}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block header_content %}{% endblock %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="login_top clearfix">
		<a href="../static/index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>
	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ username }}">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember"{{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
                        {{ errmsg }}
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}天天生鲜-注册{% endblock title %}
{% block top_files %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock %}
{% block header_content %}{% endblock %}
{% block search_bar %}{% endblock %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="#">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'user:register' %}" method="post">{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>
            {{ errmsg }}
		</div>

	</div>
{% endblock body %}

templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% block right_content %}
    <div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ address.user.username }}</li>
							<li><span>联系方式：</span>{{ address.phone }}</li>
							<li><span>联系地址：</span>{{ address.addr }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                {% for sku in sku_list %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="detail.html">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% empty %}
                    无历史浏览记录
                {% endfor %}
			</ul>
		</div>
		</div>
{% endblock right_content %}

templates/user_center_order.html
{% extends 'base_user_center.html' %}
{% block right_content %}
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
            {% for order_info in order_infos %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order_info.create_time }}</li>
					<li class="col02">订单号：{{ order_info.order_id }}</li>
					<li class="col02 stress">未支付</li>		
				</ul>

				<table class="order_list_table w980">
                    {% for order_good in orderinfo. %}
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="../static/images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
			{% endfor %}
				<div class="pagenation">
					<a href="#"><上一页></a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">下一页></a>
				</div>
		</div>
{% endblock right_content %}

templates/user_center_site.html
{% extends 'base_user_center.html' %}
{% block right_content %}
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if address %}
						<dd>{{ address.addr }} （{{ address.receiver }} 收） {{ address.phone }}</dd>
                        {% endif %}
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post">{% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="receiver">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="telephone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
{% endblock right_content %}